name: Testplugin
version: '1.0-SNAPSHOT'
main: com.kinoko.testplugin.Testplugin
api-version: 1.18
authors: [ Kinoko_2K ]
website: kinoko2k.github.io

commands:
  test:
    description: Test Command.
    usage: /<command>
  asa:
    description: Asa.
    usage: /<command>

permissions:
  testplugin.player:
    default: true
  testplugin.op:
    default: op